# Neural Network with Cubic Data (multi-dimensional)
- y = x^3 -3x^2 -9x -1
- 5 hidden layers

## 1.Import Required Libraries

In [1]:
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.init as init
from torch.autograd import Variable
from visdom import Visdom
viz = Visdom()

Setting up a new session...


## 2. Data Generation

In [2]:
num_data = 1000
num_epoch = 5000

x = init.uniform(torch.Tensor(num_data,1),-10,10)
y = (x**3) - 3*(x**2) - 9*x - 1

noise = init.normal(torch.FloatTensor(num_data,1),std=3)

y_noise = y + noise

/var/folders/ws/_w1zc2m561d_76233frzs4qr0000gn/T/ipykernel_15833/3772392901.py:4: UserWarning: nn.init.uniform is now deprecated in favor of nn.init.uniform_.
  x = init.uniform(torch.Tensor(num_data,1),-10,10)
/var/folders/ws/_w1zc2m561d_76233frzs4qr0000gn/T/ipykernel_15833/3772392901.py:7: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
  noise = init.normal(torch.FloatTensor(num_data,1),std=3)


In [ ]:
import matplotlib.pyplot as plt
fig = plt.figure()
ax1 = fig.add_subplot(121)
ax1.scatter(x, y)
ax2 = fig.add_subplot(122)
ax2.scatter((x+noise), y)

In [9]:
# visualize data

input_data = torch.cat([x,y_noise],1)

win=viz.scatter(
    X = input_data,
    opts=dict(
        xtickmin=-10,
        xtickmax=10,
        xtickstep=1,
        ytickmin=0,
        ytickmax=500,
        ytickstep=1,
        markersymbol='dot',
        markercolor=np.random.randint(0, 255, num_data),
        markersize=5,
    ),
)

In [10]:
# visualize data

win=viz.scatter(
    X = torch.cat([x,y],1),
    opts=dict(
        xtickmin=-10,
        xtickmax=10,
        xtickstep=1,
        ytickmin=0,
        ytickmax=500,
        ytickstep=1,
        markersymbol='dot',
        markercolor=np.random.randint(0, 255, num_data),
        markersize=5,
    ),
)

## 3. Model & Optimizer

In [5]:


model = nn.Sequential(
            nn.Linear(1,20),
            nn.ReLU(),
            nn.Linear(20,10),
            nn.ReLU(),
            nn.Linear(10,5),
            nn.ReLU(),
            nn.Linear(5,1),
        )

loss_func = nn.L1Loss()
optimizer = optim.SGD(model.parameters(),lr=0.001)

## 4. Train 

In [6]:
loss_arr =[]
label = y_noise

for i in range(num_epoch):
    output = model(x)
    optimizer.zero_grad()

    loss = loss_func(output,label)
    loss.backward()
    
    optimizer.step()
    
    if i % 100 ==0:
        print(loss)
        
    #loss_arr.append(loss.cpu().data.numpy()[0])
    loss_arr.append(loss.item())

tensor(215.9405, grad_fn=<L1LossBackward0>)
tensor(215.8835, grad_fn=<L1LossBackward0>)
tensor(215.7777, grad_fn=<L1LossBackward0>)
tensor(215.5607, grad_fn=<L1LossBackward0>)
tensor(215.0391, grad_fn=<L1LossBackward0>)
tensor(213.1969, grad_fn=<L1LossBackward0>)
tensor(199.3727, grad_fn=<L1LossBackward0>)
tensor(137.6155, grad_fn=<L1LossBackward0>)
tensor(134.5334, grad_fn=<L1LossBackward0>)
tensor(131.1724, grad_fn=<L1LossBackward0>)
tensor(127.2196, grad_fn=<L1LossBackward0>)
tensor(121.9333, grad_fn=<L1LossBackward0>)
tensor(113.6448, grad_fn=<L1LossBackward0>)
tensor(100.4025, grad_fn=<L1LossBackward0>)
tensor(84.7289, grad_fn=<L1LossBackward0>)
tensor(91.0946, grad_fn=<L1LossBackward0>)
tensor(80.7711, grad_fn=<L1LossBackward0>)
tensor(76.3647, grad_fn=<L1LossBackward0>)
tensor(79.1123, grad_fn=<L1LossBackward0>)
tensor(72.8752, grad_fn=<L1LossBackward0>)
tensor(75.6689, grad_fn=<L1LossBackward0>)
tensor(72.7844, grad_fn=<L1LossBackward0>)
tensor(70.3355, grad_fn=<L1LossBackward0

In [7]:
param_list = list(model.parameters())
print(param_list)



[Parameter containing:
tensor([[ 0.1352],
        [-0.6038],
        [ 0.0951],
        [ 0.6843],
        [-0.7918],
        [ 0.1031],
        [-0.1151],
        [-1.1912],
        [-0.7675],
        [-0.2410],
        [-1.3133],
        [ 1.4842],
        [-0.4947],
        [-0.0849],
        [ 0.0992],
        [-0.8010],
        [-0.2533],
        [-0.6181],
        [-0.2866],
        [ 0.9080]], requires_grad=True), Parameter containing:
tensor([ 2.6210, -0.8367, -0.9455, -3.4665, -4.2471,  1.4460,  0.6000, -3.5627,
        -4.6220, -0.2629, -5.1881,  0.5237, -0.8791,  0.4128,  0.0324, -2.1363,
         0.0343, -1.2198,  1.5494, -3.6143], requires_grad=True), Parameter containing:
tensor([[ 3.7309e-02, -1.9231e-01,  3.3858e-02,  9.7521e-01, -1.0487e-01,
          1.7474e-01,  1.3886e-01, -1.0866e-01,  7.1462e-02, -1.6905e-01,
          1.6601e-01,  8.2552e-01,  2.2320e-01, -2.2040e-02,  1.0511e-01,
         -4.3289e-02, -1.0368e-01, -5.5975e-02, -2.5536e-02,  1.2129e+00],
        

## 5. Visualize Trained Output

In [8]:
win2=viz.scatter(
    X = torch.cat([x, output],1),
    opts=dict(
        xtickmin=-10,
        xtickmax=10,
        xtickstep=1,
        ytickmin=0,
        ytickmax=500,
        ytickstep=1,
        markersymbol='dot',
        markercolor=np.random.randint(0, 255, num_data),
        markersize=5,
    ),
)



## 6. Visualize Loss Graph

In [11]:
x = np.reshape([i for i in range(num_epoch)],newshape=[num_epoch,1])
loss_data = np.reshape(loss_arr,newshape=[num_epoch,1])

win3=viz.line(
    X = x,
    Y = loss_data, 
)

AssertionError: X and Y should be the same shape