# Multi-Variable Linear Regression Example with Pytorch Models (다중 변수의 선형회귀)
- 임경태
- https://sites.google.com/view/aailab

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
x_train = np.array([[2, 3, 1], 
                    [4, 8, 9], 
                    [6, 2, 7], 
                    [8, 4, 6]])
y_train = np.array([[3], 
                    [7], 
                    [5], 
                    [8]])

n_samples = x_train.shape[0]
n_features = x_train.shape[1]
losses = []

In [ ]:
import torch

In [ ]:
linear_model = torch.nn.Linear(in_features=3, out_features=1)

print(linear_model)
print(list(linear_model.parameters()))

Linear(in_features=3, out_features=1, bias=True)
[Parameter containing:
tensor([[-0.5249, -0.4097,  0.3362]], requires_grad=True), Parameter containing:
tensor([0.4389], requires_grad=True)]


In [ ]:
x_train_torch = torch.from_numpy(x_train).float()
y_train_torch = torch.from_numpy(y_train).float()
print(x_train_torch)
print(x_train_torch.shape)

tensor([[2., 3., 1.],
        [4., 8., 9.],
        [6., 2., 7.],
        [8., 4., 6.]])
torch.Size([4, 3])


In [ ]:
predicted_y = linear_model(x_train_torch)

In [ ]:
optimizer = torch.optim.SGD(linear_model.parameters(), lr=0.01)
loss_function = torch.nn.MSELoss()

In [ ]:
linear_model.train()
for idx in range(100):
  optimizer.zero_grad()
  predicted_y = linear_model(x_train_torch)
  loss = loss_function(predicted_y, y_train_torch)  
  print(loss.item())
  loss.backward()
  optimizer.step()


2.816403865814209
2.2056899070739746
1.8098071813583374
1.5423144102096558
1.3524647951126099
1.2103990316390991
1.0984787940979004
1.006229043006897
0.9273727536201477
0.8581022024154663
0.7960625290870667
0.7397587895393372
0.688209593296051
0.6407400369644165
0.5968630909919739
0.5562084317207336
0.518480658531189
0.4834330081939697
0.45085421204566956
0.42055633664131165
0.3923720121383667
0.36614805459976196
0.3417452573776245
0.3190343976020813
0.29789698123931885
0.2782227694988251
0.2599097192287445
0.24286310374736786
0.22699442505836487
0.21222274005413055
0.19847078621387482
0.18566837906837463
0.17374970018863678
0.16265353560447693
0.15232260525226593
0.1427040994167328
0.13374847173690796
0.12540996074676514
0.11764618009328842
0.11041662096977234
0.10368462651968002
0.09741581976413727
0.09157822281122208
0.08614173531532288
0.08107872307300568
0.07636329531669617
0.07197145372629166
0.06788069009780884
0.06407038867473602
0.060520827770233154
0.05721418932080269
0.05413